config/routes.rb
# frozen_string_literal: true

# == Route Map
#
#
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'public#index'
  get :search, controller: :public

  resources :users do
    member do
      delete 'delete_image/image_id', action: 'delete_image', as: 'delete_image'
    end
  end

  # resources :teams do
  #   member do
  #     post 'add_member', action: 'add_member', as: 'add_member'
  #   end
  # end

  resources :ideas do
    resources :comments
    resources :feedbacks
    member do
      patch 'like', to: 'ideas#like'
    end
  end
  post '/ideas/:id/subscribe', to: 'subscribe_idea#subscribe', as: 'subscribe_idea'
  post '/ideas/:id/unsubscribe', to: 'subscribe_idea#unsubscribe', as: 'unsubscribe_idea'

  get 'layouts/footer/:page', to: 'pages#show', as: 'pages'

  resources :users, only: [:index] do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end
end

app/models/idea.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: ideas
#
#  id                      :bigint           not null, primary key
#  idea_name               :string(225)      not null
#  idea_description        :string           not null
#  need                    :string           not null
#  geo                     :string           not null
#  problem                 :string(225)      not null
#  industry                :string           not null
#  visible                 :boolean          not null
#  teams_id                :bigint
#  users_id                :bigint
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  cached_votes_total      :integer          default(0)
#  cached_votes_score      :integer          default(0)
#  cached_votes_up         :integer          default(0)
#  cached_votes_down       :integer          default(0)
#  cached_weighted_score   :integer          default(0)
#  cached_weighted_total   :integer          default(0)
#  cached_weighted_average :float            default(0.0)
#
class Idea < ApplicationRecord
  has_many :feedbacks, dependent: :destroy, foreign_key: :ideas_id, inverse_of: :idea
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :subscribe_ideas, dependent: :destroy, foreign_key: :ideas_id, inverse_of: :idea
  belongs_to :user, inverse_of: :ideas, foreign_key: :users_id
  belongs_to :team, inverse_of: :ideas, foreign_key: :teams_id, optional: true

  validates :idea_name, :need, :geo, :industry, presence: true, length: { maximum: 50 }
  validates :idea_description, :problem, presence: true, length: { maximum: 300 }
  validates :visible, inclusion: { in: [true, false] }
  acts_as_votable
  is_impressionable

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  INDUSTRY = %w(Art
                Comics
                Crafts
                Dance
                Design
                Film&Video
                Food
                Games
                Journalism
                Music
                Photography
                Publishing
                Technology
                Theater).freeze

  GEO = ['Asia', 'Europe', 'Africa', 'Australia', 'North America', 'South America', 'Global'].freeze

  NEED = ['Funding', 'Mentoring', 'Marketing strategy', 'Team members'].freeze

  def self.impressions
    Impression.where(impressionable_type: 'Idea')
  end

  settings index: { number_of_shards: 1 } do
    mapping dynamic: 'false' do
      indexes :id, type: :integer
      indexes :idea_name, type: :text, analyzer: :english
      indexes :idea_description, type: :text, analyzer: :english
      indexes :need, type: :text, analyzer: :english
      indexes :geo, type: :text, analyzer: :english
      indexes :problem, type: :text, analyzer: :english
      indexes :industry, type: :text, analyzer: :english
      indexes :topic, type: :keyword
    end
  end

  def self.our_first_query(query)
    search(query: { multi_match: { query: query, fields: %w(idea_name idea_description^5) } })
  end
end

app/controllers/ideas_controller.rb
# frozen_string_literal: true

class IdeasController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_idea, only: [:edit, :update]

  def index
    @ideas = Idea.order(created_at: :desc)
  end

  def new
    @idea = Idea.new
    special_users = TeamMember.where(is_creator: true, users_id: current_user.id).map do |team_member|
      [team_member.team.team_name,
       team_member.team.id]
    end
    @possible_teams = special_users.insert(0, ['none', nil])
  end

  def show
    @idea = Idea.find(params[:id])
    authorize @idea
    impressionist(@idea)
  end

  def edit; end

  def update
    if @idea.update(idea_params)
      redirect_to action: :index
      flash[:notice] = 'Update idea!'
    else
      errors_messages
      render :edit
    end
  end

  def create
    @idea = Idea.new(idea_params)
    @idea.user = current_user
    if @idea.save
      redirect_to @idea
      flash[:notice] = "The #{@idea.idea_name} is created!"
    else
      redirect_to action: :index
      errors_messages
    end
  end

  def destroy
    @idea = Idea.find(params[:id])
    authorize @idea
    if @idea.destroy
      redirect_to @idea
      flash[:notice] = "The #{@idea.idea_name} is deleted!"
    else
      errors_messages
    end
  end

  def like
    @idea = Idea.find(params[:id])
    if current_user.voted_up_on? @idea
      @idea.downvote_by current_user
    elsif current_user.voted_down_on? @idea
      @idea.upvote_by current_user
      # else # not voted
      #   @idea.upvote_by current_user
    end
    respond_to do |format|
      format.js
    end
  end

  def search
    return if query.blank?

    @posts = Post.our_first_query(query)
  end

  private

  def idea_params
    params.require(:idea).permit(:idea_name, :idea_description, :need, :problem, :geo, :industry, :visible, :teams_id)
  end

  def errors_messages
    flash[:error] = @idea.errors.full_messages
  end

  def set_idea
    @idea = Idea.find(params[:id])
  end
end

app/helpers/ideas_helper.rb
# frozen_string_literal: true

module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_with model: @idea do |form| %>
  <div class="form-group">
    <%= form.label :idea_name %>
    <%= form.text_field :idea_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :idea_description %>
    <%= form.text_field :idea_description, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :need %>
    <%= form.select :need, options_for_select(Idea::NEED)%>
  </div>

  <div class="form-group">
    <%= form.label "Location" %>
    <%= form.select :geo, options_for_select(Idea::GEO)%>
  </div>

  <div class="form-group">
    <%= form.label :industry %>
    <%= form.select :industry, options_for_select(Idea::INDUSTRY)%>
  </div>


  <div class="form-group">
    <%= form.label :problem %>
    <%= form.text_field :problem, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :Team%>
    <%= form.select :teams_id, @possible_teams%>
  </div>

  <%= form.check_box :visible, {class: 'visible-checkbox'}, false, true%>
  <%= form.label "Save as Draft", for:"visible-checkbox", class: "visible-checkbox" %>

  <div class="actions">
    <br>
    <%= form.submit 'Create idea', class: 'btn btn-outline-primary'%>
    <%= link_to 'Back', :back, class: 'btn btn-outline-secondary'%>
  </div>

<% end %>

app/views/ideas/_like_link.html.erb
<%= link_to like_idea_path(idea), method: :patch, remote: true, id: "like-link-#{idea.id}" do %>
  <% if current_user.voted_up_on?(idea) %>
    UP voted
    <b>
      <%= idea.cached_votes_up %>
    </b>
    DOWN vote
    <b><%= idea.cached_votes_down %></b>

  <% elsif current_user.voted_down_on?(idea) %>
    UP vote
    <b>
      <%= idea.cached_votes_up %>
    </b>
    DOWN voted
    <b><%= idea.cached_votes_down %></b>
  <% else %>
    UP
    <b>
      <%= idea.cached_votes_up %>
    </b>
    DOWN
    <b><%= idea.cached_votes_down %></b>
  <% end %>
<% end %>

app/views/ideas/index.html.erb
<body>
<main>
  <div class="row">
    <div class="col s6">
      <h1>Ideas</h1>
    </div>
    <div class="col s6">
      <% if user_signed_in? %>
    <h1 class="right"><%= link_to "New", new_idea_path(@idea), class: 'btn btn-primary' %></h1>
        <% end %>
    </div>
  </div>
</main>

<div class="row">
  <table class="table table-bordered table-hover">
      <div class="post-preview">
        <h4 class="post-title titleFont">
          <% if user_signed_in? %>
            <% @ideas.each do |record| %>
              <tr>
                <% unless !record.visible && record.users_id != current_user.id %>
                  <td>
                    <%= link_to record.idea_name, idea_path(record), method: :get %>
                  </td>
                  <td>
                    <% unless record.visible %>
                        [draft]
                    <% end %>
                  </td>
                  <%if record.users_id == current_user.id %>
                    <td class="table-row">
                      <% if policy(record).destroy? %>
                        <%= link_to "Destroy", idea_path(record),
                                    method: :delete,
                                    data: { confirm: "Are you sure?" },
                                    class: 'btn btn-outline-danger' %>
                      <% end %>
                    </td>
                    <td class="table-row">
                      <% if policy(record).update? %>
                        <%= link_to "Edit", edit_idea_path(record), class: 'btn btn-primary' %>
                      <% end %>
                    </td>
                    <td class="table-row">
                      <% if current_user %>
                        <%= content_tag "div", id: "like-link-#{record.id}" do %>
                          <%#binding.pry %>
                          <%#= render 'ideas/like_link', post: record %>
                        <% end %>
                      <% end %>
                    </td>
                  <% end %>
                <% end %>
              </tr>
            <%end %>
          <% else %>
            <div class="row">
              <div class="col">
                <p>For further viewing, you should sign in:</p>
                <%= link_to "Sign in", new_user_session_path, class: 'btn btn-outline-primary' %>
              </div>
            </div>
          <% end %>
        </h4>
      </div>

  </table>
</div>
</div>
</body>

<h1>Posts</h1>
<% @ideas.each do |idea| %>
  <%= idea.idea_name %>
  <% if current_user %>
    <%= content_tag "div", id: "like-link-#{idea.id}" do %>
      <%= render 'ideas/like_link', idea: idea %>
    <% end %>
  <% end %>
  <hr>
<% end %>

app/views/ideas/like.js.erb
document.getElementById("like-link-<%= @idea.id %>").innerHTML = "<%= j render "ideas/like_link", idea: @idea %>";

app/views/ideas/new.html.erb
<body>
  <main><h1>New Idea</h1></main>

  <div class="row">
    <br>
    <%= render "form", idea: @idea %>
  </div>
</body>

app/views/ideas/show.html.erb
<main>
  <div class="row">
    <div class="col s6">
      <h1 class="head-name">
        <%= @idea.idea_name %>
      </h1>
    </div>
    <div class="col s6">
      <% unless @idea.visible %>
        <h1 class="draft-name">[Draft]</h1>
      <% end %>
    </div>
  </div>
    <h4><%= @idea.idea_description %></h4>
  <div class="col s12">
    <ul class="tabs" id="tabs">
      <li class="tab col s3"><a href="#tabs-1">About</a></li>
      <li class="tab col s3"><a href="#tabs-2">Team</a></li>
      <li class="tab col s3"><a href="#tabs-3">Sponsors</a></li>
      <li class="tab col s3"><a href="#tabs-4">Statistics</a></li>
    </ul>
  </div>

  <div id="tabs-1" class="col s12">
    <div class="row">
      <div class="col s10">
        <br>
        <p>Industry: <%= @idea.industry %></p>
        <p>Location: <%= @idea.geo %></p>
        <p>Problem: <%= @idea.problem %></p>
        <p>Need: <%= @idea.need %></p>
      </div>
    </div>
  </div>

  <div id="tabs-2" class="col s12">
    <div class="col s6">
      <%if @idea.team %>
        <table>
          <thead>
          <tr>
            <th scope="col">Name</th>
          </tr>
          </thead>
          <% @idea.team.users.each do |team_user|%>
            <tr>
              <td><%=team_user.first_name %>
                <%=team_user.last_name %></td>
            </tr>
          <%end %>
          <h4>Team:</h4>
        </table>
      <%end %>
    </div>  </div>

  <div id="tabs-3" class="col s12">
    <h5>Sponsors's contacts:</h5>
    <% @idea.subscribe_ideas.each do |sub_idea|%>
      <% if sub_idea.user.sponsor %>
        <p><%= sub_idea.user.first_name %> <%= sub_idea.user.last_name %>:</p>
        <p><%= sub_idea.user.email%></p>
        <p><%= sub_idea.user.sponsor.opportunity %></p>
      <% end %>
      <br>
    <% end %>
  </div>

  <div id="tabs-4" class="col s12">
    <h5>Statistics:</h5>
    <%sponsors = [] %>
    <% @idea.subscribe_ideas.each do |sub_idea|%>
      <% sponsors << sub_idea.user.sponsor_id %>
    <% end %>
    <p>Number of subscribed sponsors: <%= sponsors.count %></p>
    <p>Views: <%= PageView.all_views(@idea.id)  %></p>
    <p>Unique views: <%= PageView.uniq_all_views(@idea.id)%></p>
  </div>

    <div class="row">
      <h5>Comments:</h5>
      <%= render 'comments/comment', idea: @idea %>
      <% if user_signed_in? && @idea.visible%>
        <h6>Add a comment:</h6>
        <%= render 'comments/form', idea: @idea %>

    </div>
        <% if current_user.subscribe_ideas.where(ideas_id: @idea.id).exists? %>
          <h5><%= link_to "UnSubscribe", unsubscribe_idea_path(@idea), method: ':post', class: 'btn btn-primary' %></h5>
        <% else %>
          <h5><%= link_to "Subscribe", subscribe_idea_path(@idea), method: ':post', class: 'btn btn-primary' %></h5>
        <% end %>
      <% end %>
  <div class="row">
    <div class="col s4">
      <p>Owner: <%= @idea.user.first_name%> <%=@idea.user.last_name %></p>
    </div>
  </div>
    <div class="row">
      <%= render @idea.feedbacks %>
    </div>
      <div class="col s4">
        <% @idea.feedbacks.where(users_id: current_user.id).each do |feedback| %>
          <% if feedback.user == current_user %>
            <%=  link_to 'Add Rating', new_idea_feedback_path(@idea) %>
          <% end %>
        <%  end %>
      </div>
</main>