config/routes.rb
# frozen_string_literal: true

# == Route Map
#
#
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'public#index'
  get :search, controller: :public

  resources :users do
    member do
      delete 'delete_image/image_id', action: 'delete_image', as: 'delete_image'
    end
  end

  # resources :teams do
  #   member do
  #     post 'add_member', action: 'add_member', as: 'add_member'
  #   end
  # end

  resources :ideas do
    resources :comments
    resources :feedbacks
    member do
      patch 'like', to: 'ideas#like'
    end
  end
  post '/ideas/:id/subscribe', to: 'subscribe_idea#subscribe', as: 'subscribe_idea'
  post '/ideas/:id/unsubscribe', to: 'subscribe_idea#unsubscribe', as: 'unsubscribe_idea'

  get 'layouts/footer/:page', to: 'pages#show', as: 'pages'

  resources :users, only: [:index] do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end
end

app/views/layouts/nav/_public.html.erb
<nav class="light-blue lighten-1" role="navigation">
  <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo">IDEA BOX</a>
    <ul id="dropdown1" class="dropdown-content">
      <li><%= link_to "Users", users_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "My Profile", current_user %></li>
      <% end %>
      <li class="divider"></li>
      <li><% if user_signed_in? %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete%>
        <% else %>
          <%= link_to "Log in", new_user_session_path %>
      <% end %>
      </li>
    </ul>
    <ul id="nav-mobile" class="right hide-on-med-and-down">

      <li><%= link_to "Teams", teams_path %></li>
      <li><%= link_to "Ideas", ideas_path%></li>
      <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Profile<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
    <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
  </div>
</nav>