config/routes.rb
# frozen_string_literal: true

# == Route Map
#
#
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'public#index'
  get :search, controller: :public

  resources :users do
    member do
      delete 'delete_image/image_id', action: 'delete_image', as: 'delete_image'
    end
  end

  # resources :teams do
  #   member do
  #     post 'add_member', action: 'add_member', as: 'add_member'
  #   end
  # end

  resources :ideas do
    resources :comments
    resources :feedbacks
    member do
      patch 'like', to: 'ideas#like'
    end
  end
  post '/ideas/:id/subscribe', to: 'subscribe_idea#subscribe', as: 'subscribe_idea'
  post '/ideas/:id/unsubscribe', to: 'subscribe_idea#unsubscribe', as: 'unsubscribe_idea'

  get 'layouts/footer/:page', to: 'pages#show', as: 'pages'

  resources :users, only: [:index] do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  first_name             :string(225)      not null
#  last_name              :string(225)      not null
#  email                  :string           default(""), not null
#  role_id                :bigint
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sponsor_id             :bigint
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :github, :google_oauth2, :linkedin]

  attr_accessor :auth, :current_user
  attr_writer :sponsor_profile_exists

  before_validation :set_default_role, on: [:create]

  belongs_to :role
  has_many :subscribe_ideas, dependent: :destroy, foreign_key: :users_id, inverse_of: :user
  has_many :authorizations, dependent: :destroy
  has_many :team_members, dependent: :destroy, foreign_key: :users_id, inverse_of: :user
  has_many :teams, through: :team_members, dependent: :destroy
  has_many :ideas, dependent: :destroy, inverse_of: :user, foreign_key: :users_id
  has_many :feedbacks, dependent: :destroy, foreign_key: :users_id, inverse_of: :user
  has_many :comments, dependent: :destroy
  belongs_to :sponsor, optional: true

  validates :first_name, :last_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 250 }, format: { with: VALID_EMAIL_REGEX }

  accepts_nested_attributes_for :sponsor

  has_one_attached :profile_picture, dependent: :destroy
  validates :profile_picture, content_type: [:png, :jpg, :jpeg]

  acts_as_voter

  def sponsor_profile_exists
    !!sponsor_id
  end

  def self.create_user
    @auth = request.env['omniauth.auth']
    auth = @auth
    joins(:authorizations).where(authorizations: { provider: auth.provider,
                                                   uid: auth.uid }).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.name
    end
  end

  def self.create_own_user(auth)
    User.create!(
      email: auth.info.email,
      password: Devise.friendly_token[0, 20],
      first_name: auth.info.name.split.first,
      last_name: auth.info.name.split.last
    )
  end

  def self.detect_auth(auth)
    Authorization.find_or_initialize_by(
      provider: auth.provider,
      uid: auth.uid.to_s,
      secret: auth.credentials.secret
    ) do |db_auth|
      db_auth.token = auth.credentials.token
    end
  end

  def self.from_omniauth(auth, current_user)
    authorization = detect_auth(auth)
    if authorization.user.blank?
      user = current_user.nil? ? User.where(email: auth['info']['email']).first : current_user
      user = create_own_user(auth) if user.blank?
      authorization.user_id = user.id
      authorization.save!
    end
    authorization.user
  end

  private

  def set_default_role
    self.role ||= Role.find_or_create_by(role: 'user')
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :validate_authorization_for_user, only: [:edit, :update]

  # GET /users/1
  def index
    @users = User.order(created_at: :desc)
    authorize @users
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
    @user.sponsor ||= Sponsor.new
  end

  # PATCH/PUT /users/1
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      destroy_sponsor_profile if profile_should_destroy?
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def impersonate
    @user = User.find(params[:id])
    impersonate_user(@user)
    flash[:notice] = 'Impersonated success!'
    redirect_to root_path
  end

  def stop_impersonating
    stop_impersonating_user
    redirect_to root_path
  end

  def delete_image
    image = ActiveStorage::Attachment.find(params[:id])
    if current_user == image.record
      image.purge
      redirect_back(fallback_location: request.referer)
    else
      redirect_to root_url, notice: 'Oops!'
    end
  end

  private

  def destroy_sponsor_profile
    @user.sponsor.destroy!
  end

  def profile_should_destroy?
    !user_params[:sponsor_profile_exists] && @user.sponsor_id
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def validate_authorization_for_user
    redirect_to root_path unless @user == current_user
  end

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :role_id,
                                 :profile_picture,
                                 :sponsor_profile_exists,
                                 :password,
                                 sponsor_attributes: [:industry,
                                                      :geo,
                                                      :opportunity,
                                                      :id])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_error.html.erb
<% user.errors.full_messages_for(field).each do |message| %>
  <div class="alert alert-danger"><%= message %></div>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
    <%= render 'users/error', user: user, field: :first_name %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
    <%= render 'users/error', user: user, field: :last_name %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
    <%= render 'users/error', user: user, field: :email %>
  </div>

  <div class="form-group">
    <% if user.profile_picture.attached?  && user.profile_picture.representable?%>
    <%= image_tag user.profile_picture.variant(resize: '100x100'). processed %>
    <div class="upload-hider-labels">
      <%= link_to '#', class: 'replace-upload' do %>
      Replace Current Image
    <% end %>
    <span class="separator-bar">|'</span>
      <%= link_to 'Remove Image without replacing',
                  delete_image_user_url(image_id: user.profile_picture.id),
                  method: :delete,
                  data: { confirm: 'Are you sure?' },
                  class: 'remove-upload'
      %>
    </div>
    <% else %>
      <div class="profile-picture no-profile-picture"></div>
    <% end %>
    <div class="upload-hider-fields">
      <%= form.file_field :profile_picture, class: 'form-control' %>
    </div>
  </div>

    <%= form.check_box :sponsor_profile_exists,  {class: 'checkbox-sponsor'}, true, false %>
    <%= form.label "Sponsor", for:"checkbox-sponsor", class: "checkbox-sponsor" %>

  <%= form.fields_for :sponsor do |sponsor| %>
    <div class="form-group-for-disable">
      <%= sponsor.label "Location" %>
      <%= sponsor.select :geo, options_for_select(Idea::GEO, user.sponsor.geo), { :class => 'select-form-user' }%>
    </div>

    <div class="form-group-for-disable">
      <%= sponsor.label :industry %>
      <%= sponsor.select :industry, options_for_select(Idea::INDUSTRY, user.sponsor.industry)%>
    </div>

    <div class="form-group-for-disable">
      <%= sponsor.label :opportunity %>
      <%= sponsor.select :opportunity, options_for_select(Idea::NEED, user.sponsor.opportunity)%>
    </div>
  <% end %>

  <div>
    <%= form.submit 'Update profile', class: 'btn btn-outline-primary' %>
    <%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'users/form', user: @user %>

app/views/users/index.html.erb
<body>
<main>
  <h1>Users</h1>
</main>

<div class="row">
  <table class="table table-bordered table-hover">
      <div class="post-preview">
        <h4 class="post-title titleFont">
          <% @users.each do |user| %>
            <tr>
              <td class="table-row"></td>
              <td><%=link_to user.first_name, user %> <%= link_to user.last_name, user %></td>
          <% end %>
            </tr>
        </h4>
      </div>
      <hr>
  </table>
</div>
</div>
</body>

app/views/users/show.html.erb
<% if user_signed_in? %>
  <div class="row">
    <div class="col">
      <h1><%= @user.first_name %> <%= @user.last_name %></h1>
      <p>Role: <%= @user.role.role %></p>
      <% if policy(@user).update? %>
        <%= link_to "Edit", edit_user_path(@user), class: 'btn btn-outline-primary' %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col">
    <% if current_user != true_user %>
      You (<%= true_user.first_name %> <%= true_user.last_name %>) are signed in as <%= current_user.first_name %> <%= current_user.last_name %>
      <%= link_to "Back to admin", stop_impersonating_users_path, method: :post %>
    <% else %>
      <% if policy(@user).impersonate? %>
        Sign in as <%= link_to @user.first_name, impersonate_user_path(@user), method: :post %>
        <%= link_to @user.last_name, impersonate_user_path(@user), method: :post %>
      <% end %>
    <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-4">
      <% if @user.profile_picture.attached?%>
        <%= image_tag url_for(@user.profile_picture.variant(resize: '500x500').processed), class: 'img-fluid'%>
      <% else %>
        <div class="profile-picture no-profile-picture"></div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col">
      <h1><%= @user.first_name %> <%= @user.last_name %></h1>
      <p>For further viewing, you must register:</p>
      <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-outline-primary' %>
    </div>
  </div>
<% end %>