config/routes.rb
# frozen_string_literal: true

# == Route Map
#
#
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'public#index'
  get :search, controller: :public

  resources :users do
    member do
      delete 'delete_image/image_id', action: 'delete_image', as: 'delete_image'
    end
  end

  # resources :teams do
  #   member do
  #     post 'add_member', action: 'add_member', as: 'add_member'
  #   end
  # end

  resources :ideas do
    resources :comments
    resources :feedbacks
    member do
      patch 'like', to: 'ideas#like'
    end
  end
  post '/ideas/:id/subscribe', to: 'subscribe_idea#subscribe', as: 'subscribe_idea'
  post '/ideas/:id/unsubscribe', to: 'subscribe_idea#unsubscribe', as: 'unsubscribe_idea'

  get 'layouts/footer/:page', to: 'pages#show', as: 'pages'

  resources :users, only: [:index] do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end
end

app/models/feedback.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: feedbacks
#
#  id         :bigint           not null, primary key
#  rating     :integer          not null
#  users_id   :bigint
#  ideas_id   :bigint
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  reaction   :boolean
#
class Feedback < ApplicationRecord
  belongs_to :user, foreign_key: :users_id, inverse_of: :feedbacks
  belongs_to :idea, foreign_key: :ideas_id, inverse_of: :feedbacks

  validates :reaction, inclusion: { in: [true, false, nil] }
  validates :rating, numericality: true

  REACTION = [true, false, nil].freeze
end

app/controllers/feedbacks_controller.rb
# frozen_string_literal: true

class FeedbacksController < ApplicationController
  before_action :find_idea
  before_action :find_feedback, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @feedback = Feedback.new
  end

  def create
    @feedback = Feedback.new(feedback_params)
    @feedback.ideas_id = @idea.id
    @feedback.users_id = current_user.id
    if @feedback.save
      redirect_to idea_path(@idea)
    else
      render 'new'
    end
  end

  def update
    if @feedback.update(feedback_params)
      redirect_to idea_path(@idea)
    else
      render 'edit'
    end
  end

  def edit
    # edit
  end

  def destroy
    @feedback.destroy
    redirect_to idea_path(@idea)
  end

  private

  def feedback_params
    params.require(:feedback).permit(:rating, :reaction)
  end

  def find_idea
    @idea = Idea.find(params[:idea_id])
  end

  def find_feedback
    @feedback = Feedback.find(params[:id])
  end
end

app/views/feedbacks/_feedback.html.erb
<% if user_signed_in? %>
  <% if feedback.users_id == current_user.id %>
    <div id="rate<%= feedback.id %>"></div>
    <%= link_to 'Edit', edit_idea_feedback_path(feedback.idea, feedback) %>
    <%= link_to 'Delete', idea_feedback_path(feedback.idea, feedback), method: :delete, data: {
      confirm: "Are you sure?" } %>

  <% end %>
<% end %>
<script>
    $('#rate<%= feedback.id%>').raty({
        size      : 36,
        starOff   : '<%= asset_path('star-off.png') %>',
        starOn    : '<%= asset_path('star-on.png') %>',
        starHalf  : '<%= asset_path('star-half.png') %>',
        readOnly: true,
        score: <%= feedback.rating %>,
    });
</script>

app/views/feedbacks/_form.html.erb
<%= form_with model: [ @idea, @idea.feedbacks.build ] do |form| %>

    <div class="form-group">
    <%= form.hidden_field(:reaction, :value => nil )%>
  </div>

  <div class="form-group row" id="star">
    <%= form.label :rating,'Evaluation', class:'col-md-3 col-form-label' %>
    <%= form.hidden_field :rating, id: :review_star %>
  </div>

  <!--Rating javascript-->
  <script>
      $('#star').raty({
          size     : 36,
          numberMax: 5,
          number: 5,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',

          scoreName: 'feedback[rating]',
          half: false,
      });
  </script>


  <div>
    <%= form.submit 'Submit', class: 'btn btn-outline-primary' %>
    <%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

<!--<script>-->
<!--    $('#rating-form').raty({-->
<!--        path: '/assets/',-->
<!--    scoreName: 'idea_feedback[rating]'-->
<!--    });-->
<!--</script>-->

app/views/feedbacks/edit.html.erb
<h1>Edit Rating</h1>

<%= form_with model: [ @idea, @feedback ] do |form| %>

  <div class="form-group">
    <div class="form-group row" id="star">
      <%= form.label :rating,'Evaluation', class:'col-md-3 col-form-label' %>
      <%= form.hidden_field :rating, id: :review_star %>
    </div>

    <!--Rating javascript-->
    <script>
        $('#star').raty({
            size     : 36,
            numberMax: 5,
            number: 5,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',

            scoreName: 'feedback[rating]',
            half: false,
        });
    </script>
    <%= form.hidden_field(:reaction, :value => nil )%>
  </div>

  <div>
    <%= form.submit 'Submit', class: 'btn btn-outline-primary' %>
    <%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/feedbacks/new.html.erb
<body>
<main><h1>New Rating</h1></main>

<div class="row">
  <br>
  <%= render "form", feedback: @feedback %>
</div>
</body>